name: Maven Resolve
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  resolve:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '8.0.352'
          distribution: 'temurin'
      - name: Maven Resolve
        run: |
          version=$(cat VERSION)
          mkdir verify || exit 1
          mv .github/templates/verify-pom.xml verify/pom.xml
          cd verify || exit 1
          sed -i "s/VERSION/${version}/g" pom.xml
          cat pom.xml || exit 1
          mvn dependency:resolve -U
